### PR TITLE
Add support for Debian bullseye

### PR DESCRIPTION
**Pull request by sim6**

### CODE REVIEW

**Comment by marcospb19** [comment]
Hi @sim6, I was reviewing my repositories to check if I've missed any PRs, and then I found this!

I'm so sorry I didn't saw it earlier, thank you so much for making it, I really appreciate it.

Sorry for the late merge.

**Comment by sim6** [comment]
Thanks, but I moved to [Alacritty](https://en.wikipedia.org/wiki/Alacritty) since https://github.com/thestinger/termite/issues/760#issuecomment-716676504.

**Comment by marcospb19** [comment]
I haven't moved to `alacritty` yet, but I see that `termite` has been dead for a while now, I created an fork to add modularized configuration but then realized that moving away from it would be the best alternative.

**Comment by marcospb19** [comment]
I might as well mention `alacritty` in the `README`, and say why I'm recommending it.

**Pull request merged**
